### ISSUE TITLE
Silent build: check template variables

### ISSUE THREAD

**Issue by SilviaAmAm** [GemeenteUtrecht/bptl#113]
When a silent document is built, all template variables need to be submitted to Xential when creating a ticket.
These are currently passed to BPTL as task variables, but no check is done to see if all of them are present.

**To Do**
Request from Xential which template variables a template needs and then check that they match those in the task variables. This will require the new Xential endpoint for retrieving template variables.

**Comment by sergei-maertens** [comment]
This won't happen - it's not possible for Xential to provide such an endpoint. Had a call with Xential on Thursday where this was explained.
