### ISSUE TITLE
Implement a work unit to set a Rol for a zaak

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/bptl#70]
There should be a work unit to set a rol for a zaak, mapping to the [`rol_create`](https://zaken-api.vng.cloud/api/v1/schema/#operation/rol_create) operation.

Input parameters for the task:

- `zaakUrl`: the URL reference of the zaak to create a rol for
- `omschrijving`: the roltype omschrijving, use this in combination with `zaak.zaaktype` to find the correct `rolType` reference
- `betrokkene`: a JSON object containing the rest of the body for `rol_create`

In `bptl.work_units.zgw.tasks.zaak.CreateZaakTask.create_rol` you can see an existing implementation that gets you there 90% of the way.

`zaakUrl` and `omschrijving` should be used to complete the rest of the body `betrokkene` to POST to the API.

Upstream issue: https://github.com/GemeenteUtrecht/ZGW/issues/518

**Comment by annashamray** [comment]
the requirements are updated with two required input vars: `betrokkeneType` and `roltoelichting`

**Comment by annashamray** [comment]
changes are reverted
